# Default values for workflow-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requestsCpu: "0.1"
  requestsMemory: "2816M"
  limitsCpu: "1"
  limitsMemory: "3G"
  serviceAccountName: "workflow"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  configmap: "workflow-config"
  appName: "workflow"
  workflowAirflowSecretName: "workflow-airflow-secret"
  workflowPostgresSecretName: "workflow-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"
  onPremEnabled: false
  domain: ""
