variables:
  OSDU_GCP_SERVICE: workflow
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_TEST_SUBDIR: testing/$OSDU_GCP_SERVICE-test-$OSDU_GCP_VENDOR
  OSDU_GCP_HELM_CONFIG_SERVICE: workflow-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: workflow-deploy
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: >
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.osdu_airflow_url=$OSDU_GCP_AIRFLOW_URL
    --set data.shared_tenant_name=$TENANT_NAME
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.osdu_airflow_url=$OSDU_GCP_AIRFLOW_URL
    --set data.shared_tenant_name=$TENANT_NAME
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA
    --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s
