variables:
  OSDU_BUILD_SUBDIR: provider/file-gcp-datastore
  # OSDU_INT_TEST_SUBDIR: testing/file-test-core
  OSDU_SERVICE: workflow
  OSDU_RECORDS_ROOT_URL: https://os-storage-dot-nice-etching-277309.uc.r.appspot.com/api/storage/v2
  OSDU_VENDOR: gcp-datastore
  OSDU_APPLICATION_NAME: os-workflow
  OSDU_ENV_VARS: GCP_AIRFLOW_URL=$OSDU_AIRFLOW_URL,OSDU_ENTITLEMENTS_URL=$OSDU_ENTITLEMENTS_URL --vpc-connector=$OSDU_VPC_CONNECTOR 
  OSDU_ENVIRONMENT: dev
  OSDU_PORT: 8080

include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'standard-setup.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'build/maven.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/gitlab-ultimate.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'scanners/fossa.yml'

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'publishing/pages.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    ref: 'osdu-gcp-cloudrun'
    file: 'cloud-providers/osdu-gcp-cloudrun.yml'
