variables:
  IBM_BUILD_SUBDIR: provider/workflow-ibm
  IBM_INT_TEST_SUBDIR: testing/workflow-test-ibm

  AWS_BUILD_SUBDIR: provider/workflow-aws/build-aws
  AWS_TEST_SUBDIR: testing/workflow-test-aws
  AWS_SERVICE: ingestion-workflow
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-ingestion-workflow
  AWS_SERVICE_NAMESPACE: osdu-ingest

  # Start azure specific variables
  AZURE_SERVICE: ingestion-workfow
  AZURE_BUILD_SUBDIR: provider/workflow-azure
  AZURE_TEST_SUBDIR: testing/workflow-test-azure
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD
  # End azure specific variables

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - local: "devops/gcp/pipeline/override-stages.yml"
