apiVersion: v2
name: os-ingestion-workflow
version: __CHART_VERSION__
kubeVersion: "v1.23.x-x-x"
description: Ingestion Workflow Helm chart for Kubernetes
type: application
appVersion: __VERSION__
dependencies:
  - name: osdu-aws-lib
    version: 0.2.0
    repository:  __HELM_REPO__/osdu-aws-lib/
deprecated: false
