# Default values for workflow-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  dataPartitionId: ""
  limitsEnabled: true
  tier: ""
  autoscalingMode: "cpu"

data:
  #Configmap variables
  logLevel: "ERROR"
  partitionHost: "http://partition"
  entitlementsHost: "http://entitlements"
  schemaHost: "http://schema"
  legalHost: "http://legal"
  osduAirflowUrl: "http://airflow:8080"
  workflowHost: "http://workflow"
  dagNames:
    - csv_ingestion
    - Energistics_xml_ingest
    - manifest_ingestion
    - Osdu_ingest
    - Segy_to_vds_conversion_sdms
    - Segy_to_zgy_conversion
    - Osdu_ingest_by_reference
    - segy_to_mdio_conversion
  # Deployment variables
  requestsCpu: "60m"
  requestsMemory: "650Mi"
  limitsCpu: "1"
  limitsMemory: "3G"
  serviceAccountName: "workflow"
  bootstrapImage: ""
  bootstrapServiceAccountName: "datafier"
  image: ""
  imagePullPolicy: "IfNotPresent"
  affinityLabelsSpot:
    cloud.google.com/gke-provisioning:
      - spot
  affinityLabelsStandard:
    cloud.google.com/gke-provisioning:
      - standard

conf:
  configmap: "workflow-config"
  appName: "workflow"

istio:
  proxyCPU: "5m"
  proxyCPULimit: "200m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "256Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "50m"

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu:
    utilization: 200
    scaleUpStabilizationWindowSeconds: 30
    scaleUpValue: 200
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 150
    scaleDownValue: 100
    scaleDownPeriod: 15
  requests:
    targetType: "AverageValue"
    targetValue: 140
    scaleUpStabilizationWindowSeconds: 10
    scaleUpValue: 50
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 60
    scaleDownValue: 25
    scaleDownPeriod: 60

limits:
  maxTokens: 80
  tokensPerFill: 80
  fillInterval: "1s"
