# Default values for workflow-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false

data:
  #Configmap variables
  logLevel: "ERROR"
  partitionHost: "http://partition"
  entitlementsHost: "http://entitlements"
  osduAirflowUrl: "http://airflow:8080"
  springProfilesActive: "gcp"
  sharedTenantName: ""
  composerClient: "IAAP"
  dataPartitionId: ""
  workflowHost: "http://workflow"
  dagNames:
    - csv_ingestion
    - Energistics_xml_ingest
    - manifest_ingestion
    - Osdu_ingest
    - Segy_to_vds_conversion_sdms
    - Segy_to_zgy_conversion
  # Deployment variables
  requestsCpu: "10m"
  requestsMemory: "750Mi"
  limitsCpu: "1"
  limitsMemory: "3G"
  serviceAccountName: "workflow"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  configmap: "workflow-config"
  appName: "workflow"
  workflowAirflowSecretName: "workflow-airflow-secret"
  workflowPostgresSecretName: "workflow-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"

istio:
  proxyCPU: "10m"
  proxyCPULimit: "200m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "256Mi"
  bootstrapProxyCPU: "10m"
  bootstrapProxyCPULimit: "100m"
