apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  ENTITLEMENTS_HOST: { { .Values.data.entitlementsHost  | quote } }
  PARTITION_HOST: { { .Values.data.partitionHost  | quote } }
