apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.conf.appName | quote }}
  annotations:
    {{- if not .Values.conf.onPremEnabled }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.conf.appName | quote }}
    service: {{ .Values.conf.appName | quote }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: {{ .Values.conf.appName | quote }}
