# Default values for ingestion-workflow-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  log_level: "INFO"
  partitionHost: "http://partition"
  entitlementsHost: "http://entitlements"
  osdu_airflow_url: "http://airflow:8080"
  spring_profiles_active: "gcp"
  shared_tenant_name: ""
  # gcp
  google_audiences: ""

conf:
  configmap: "workflow-config"
  app_name: "workflow"
  on_prem_enabled: false
