apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.conf.appName }}-authz-policy
spec:
  selector:
    matchLabels:
      {{- include "ibm-workflow-deploy.selectorLabels" . | nindent 6 }}
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals:
        - '*'
    to:
    - operation:
        notPaths:
        - '*/v1/api-docs'
        - /api/workflow/v1/info
        - /api/workflow/liveness_check
        - /api/workflow/readiness_check