apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.conf.appName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  hosts:
    {{- if and .Values.conf.domain .Values.conf.onPremEnabled }}
    - {{ printf "osdu.%s" .Values.conf.domain | quote }}
    {{- else if .Values.conf.domain }}
    - {{ .Values.conf.domain | quote }}
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/workflow"
      route:
        - destination:
            port:
              number: 80
            host: "{{ .Values.conf.appName }}.{{ .Release.Namespace }}.svc.cluster.local"
