apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  OSDU_AIRFLOW_URL: {{ .Values.data.osduAirflowUrl | quote }}
  SHARED_TENANT_NAME: {{ .Values.data.sharedTenantName | quote }}
  {{- if not .Values.conf.onPremEnabled }}
  COMPOSER_CLIENT: {{ .Values.data.composerClient | quote  }}
  {{- end }}
