global:
  domain: ""
  useHttps: true
  limitsEnabled: true
  dataPartitionId: ""

data:
  # configmaps
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  # deployments
  imagePullPolicy: "IfNotPresent"
  image: ""
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "500m"
  limitsMemory: "1G"
  serviceAccountName: "partition"

conf:
  appName: "workflow"
  configmap: "partition-config"
  secret: "partition-postgres-secret"
  replicas: 1

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "100m"
  sidecarInject: "true"
