name: 'LLM Provider Detection'
description: 'Detect available LLM provider (Azure Foundry → Fallback)'

outputs:
  use_llm:
    description: 'Whether LLM is available (true/false)'
    value: ${{ steps.detect.outputs.use_llm }}
  llm_model:
    description: 'LLM model identifier (azure for Azure Foundry, empty for fallback)'
    value: ${{ steps.detect.outputs.llm_model }}

runs:
  using: "composite"
  steps:
    - name: Detect LLM provider
      id: detect
      shell: bash
      run: ${{ github.action_path }}/detect-provider.sh
      env:
        AZURE_API_KEY: ${{ env.AZURE_API_KEY }}
        AZURE_API_BASE: ${{ env.AZURE_API_BASE }}