apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  PARTITION_HOST: "{{ .Values.data.partitionHost }}"
  ENTITLEMENTS_HOST: "{{ .Values.data.entitlementsHost }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.springProfilesActive }}"
  OSDU_AIRFLOW_URL: "{{ .Values.data.osduAirflowUrl }}"
  SHARED_TENANT_NAME: "{{ .Values.data.sharedTenantName }}"
  {{- if not .Values.conf.onPremEnabled }}
  COMPOSER_CLIENT: "{{ .Values.data.composerClient }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.googleAudiences }}"
  {{- end }}
