{{- if .Values.conf.on_prem_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  name: "{{ .Values.conf.secret_name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  OSDU_AIRFLOW_USERNAME: "{{ .Values.data.osdu_airflow_username }}"
  OSDU_AIRFLOW_PASSWORD: "{{ .Values.data.osdu_airflow_password }}"
{{- end }}
