variables:
  GC_SERVICE: workflow
  GC_VENDOR: gc
  GC_ENABLE_BOOTSTRAP: "true"

download_gc_plugins:
  image: maven:3.8.3-openjdk-17-slim
  stage: build
  variables:
    GC_OSM_PACKAGE_REGISTRY_URL: "https://community.opengroup.org/api/v4/projects/1476/packages/maven"
    GC_OSM_VERSION: "0.27.1"
    GC_OQM_PACKAGE_REGISRTY_URL: "https://community.opengroup.org/api/v4/projects/1477/packages/maven"
    GC_OQM_VERSION: "0.27.1"
  artifacts:
    paths:
      - ./tmp-gc/*.jar
    when: always
    expire_in: 1 days
  script:
    - mvn dependency:copy -DrepoUrl=$GC_OSM_PACKAGE_REGISTRY_URL -Dartifact="org.opengroup.osdu:gc-osm-datastore:$GC_OSM_VERSION:jar:plugin" -Dtransitive=false -DoutputDirectory="./tmp-gc"
    - mvn dependency:copy -DrepoUrl=$GC_OQM_PACKAGE_REGISRTY_URL -Dartifact="org.opengroup.osdu:gc-oqm-pubsub:$GC_OQM_VERSION:jar:plugin" -Dtransitive=false -DoutputDirectory="./tmp-gc"
  only:
    variables:
      - $GC == '1'

gc-containerize-gitlab:
  needs: ["gc-compile-and-unit-test", "download_gc_plugins"]

gc-containerize-gcr:
  needs: ["gc-compile-and-unit-test", "download_gc_plugins"]
